### ISSUE TITLE
Documenting broadcast/clients and automatically generating secret

### ISSUE THREAD

**Issue by thefotios** [ryanj/darkslides#1]
This is awesome, I would love to user this quickstart as our official OpenShift revealjs quickstart. Two questions.
- Would you be able to document how to get the broadcast/client feature working?
- Is it possible to automatically generate a secret so that everybody will have a different version? We have a few quickstarts/carts that do this already, I can point you to some code if you'd like.

I'd like to fork this and remove your slides/themes and replace them with generic versions. Then anybody wanting to use revealjs can use this version. I think it's much better than our current version that hacks this together using php.

**Comment by tvvocold** [comment]
have u try this?
https://github.com/openshift-quickstart/reveal.js-openshift-quickstart

**Comment by ryanj** [comment]
whoa, didn't notice this issue - Sorry!

Since this is a Javascript app, I also prefer to run it in it's native environment (rather than adding PHP to the mix).

Here is an updated downstream fork of the official reveal.js repo: https://github.com/ryanj/reveal.js

Lately, I've been using http://gist-reveal.it instead, which loads presentation data from gist.github.com

Documentation regarding secret keys and broadcasting slide transitions:
- https://github.com/ryanj/gist-reveal.it#broadcasting-slide-transitions
- http://gist-reveal.it/#/4
- Broadcast by matching the server's `$REVEAL_SOCKET_SECRET` with the browser's `localStorage.secret`

New post about gist-reveal.it: http://blog.arungupta.me/reactive-html-presentations-revealjs-gist-openshift-techtip69/
